# Generated by Django 4.2.16 on 2025-01-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
