# Generated by Django 4.2.16 on 2025-01-07 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_trainer_birth_trainer_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='name',
            new_name='name_trainer',
        ),
    ]
